version: '3.3'
services:
  db:
    image: mysql:8.0
    container_name: ywts-db
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/db/conf.d:/etc/mysql/conf.d
      - ./docker/db/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_DATABASE: ywts
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  vue:
    build:
      context: ./docker/vue
    container_name: ywts-vue
    ports:
      - 8080:8080
    volumes:
      - .:/app
    working_dir: /app
    tty: true
    command: sh -c "cd assets && yarn serve"
    depends_on:
      - db

  go:
    build:
      context: ./docker/go
    container_name: ywts-go
    ports:
      - 8082:8082
    volumes:
      - .:/go/src
    working_dir: /go/src/app
    tty: true
    command: fresh
    depends_on:
      - db
  
  nginx:
    image: nginx:latest
    depends_on:
      - go
    container_name: ywts-nginx
    ports:
      - 80:80
    restart: always
    environment:
      - TZ=${NGINX_TZ}
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - vue
      - go
      - db
  
volumes:
  db_data: